yakoffka_blog_post:
    resource: "@YakoffkaBlogBundle/Controller/PostController.php"
    type:     annotation

yakoffka_blog:
    resource: "@YakoffkaBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
